### ISSUE TITLE
Inconsistent number of monomials in the zero polynomial

### ISSUE THREAD

**Issue by maidens** [MOSEK/Polyopt.jl#1]
I have been running into errors when manipulating sparse arrays of Poly objects, and I think the source of the problem is inconsistent handling of zero polynomials. Here is an example: 

``` julia
using Polyopt
x, = variables(["x"])

# define a zero polynomial 
zero = convert(Polyopt.Poly{Float64}, 0.0)
println(zero)
println(zero.m) # prints 1, as expected

# add zero polynomial to itself
zero_plus_zero = zero + zero
println(zero_plus_zero)
println(zero_plus_zero.m) # prints 0, I believe that this is undesired behavior 
```

Above, we define two different zero polynomials, one consisting of one monomial while the other has "zero monomials." Now, if we try to add these to a different polynomial, we run into trouble:

``` julia
# this works as expected 
zero + x

# this throws "LoadError: incompatible monomial bases" 
zero_plus_zero + x
```

Trying to add to the polynomial with "zero monomials" results in the error:

```
LoadError: incompatible monomial bases
while loading In[7], in expression starting on line 5

 in promote_poly at /Users/maidens/.julia/v0.4/Polyopt/src/polynomial.jl:171
 in add at /Users/maidens/.julia/v0.4/Polyopt/src/polynomial.jl:87
 in + at /Users/maidens/.julia/v0.4/Polyopt/src/polynomial.jl:97
```

This type of error leads to unpredictable and difficult to diagnose errors when manipulating arrays of Poly objects. For example:

``` julia
# this works as expected
b  = [1.0; 1.0]
A1 = [x 0.0]
y1 = A1*b

# this throws "LoadError: incompatible monomial bases"
A2 = [0.0 x]
y2 = A2*b
```

```
LoadError: incompatible monomial bases
while loading In[8], in expression starting on line 8

 in promote_poly at /Users/maidens/.julia/v0.4/Polyopt/src/polynomial.jl:171
 in add at /Users/maidens/.julia/v0.4/Polyopt/src/polynomial.jl:87
 in generic_matvecmul! at linalg/matmul.jl:413
 in * at linalg/matmul.jl:86
```

**Comment by joachimdahl** [comment]
Thank you pointing this out.  

I adjusted the `simplify()` function to return zero polynomials with n=0 and m=1, which fixes the problem you reported.

In many ways it would be simpler to only allow constant polynomials with proper monomial bases, for example specifying zero as

```
zero = 0*x^0*y^0
```

or one as

```
one = x^0*y^0
```

but many functions in julia rely on a `zero(Poly{T})` function being available.

**Comment by maidens** [comment]
It works great now. Thanks so much! 

I'll mark the issue as closed.
